Time Method implementation
bgwebagency/who-wants-to-be-a-javascriptaire pull request #30
Opened 2023-05-08 16:29 UTC by MehmetTerc

I implementated the issue

2023-05-08 16:35 UTC, MehmetTerc commented
It was the Question 33 and i make a small task to solve

2023-05-08 17:27 UTC, kirandash requested changes
Thanks for the PR! The question is nice but it doesn't meet the requirement of MCQ for this project

2023-05-08 17:27 UTC, kirandash commented on README.md
> +
Please note that the questions are supposed to be MCQ. Can you please update the question with multiple choices that user can pick from.

Please have a look at other questions for inspiration

2023-05-08 17:27 UTC, kirandash commented on .idea/checkstyle-idea.xml
Please add .idea to .gitignore file so that they are not committed to the repo.

2023-05-10 11:33 UTC, MehmetTerc commented
can you check it again

2023-05-10 12:10 UTC, kirandash commented
> can you check it again

@MehmetTerc Thanks a lot for making the adjustments. 

I made tiny adjustments to the question and answer format but still using your content. 

Also, please note that when you have already pushed the files, and then you add it to gitignore, you will have to do some additional steps to remove it from remote repository. 

Adding the steps here for your reference: 

```
git rm -r --cached .
git add .
git commit -m "clean up pushed .idea files"
git push
```

I have already done this. But adding here for your reference. 

You can read more at: https://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository

2023-05-10 12:10 UTC, merged

2023-05-10 12:11 UTC, kirandash commented
fixes #23