issue #38: Create MCQA for topic JS module, Import, Export
bgwebagency/who-wants-to-be-a-javascriptaire pull request #46
Opened 2023-05-22 18:32 UTC by Subham5401

Hi @kirandash,

I hope you're doing well. I have submitted a new pull request that adds a medium difficulty level coding question on the topic of JavaScript Modules, Import, and Export in ES6.

The question focuses on understanding the usage of named exports, default exports, and import statements in JavaScript modules. It requires the reviewer to analyze a code snippet and determine the output of the provided console.log statements.

I have provided four answer options along with a brief explanation for the correct answer. This question aims to test the reviewer's knowledge and comprehension of JavaScript module concepts.

Your feedback and suggestions are greatly appreciated. Please let me know if you have any comments or if there are any changes you would like me to make.

Thank you for your time and consideration.

Best regards,
SM

2023-05-23 09:59 UTC, kirandash requested changes
Thanks for the PR, please make the suggested changes

2023-05-23 09:59 UTC, kirandash commented on code/040/script.js
> +import calculateCircumference from './module.js';
Suggestion:

```diff
- import { PI, calculateArea } from './module.js';
- import calculateCircumference from './module.js';
+ import calculateCircumference, { PI, calculateArea } from './module.mjs'
```

2023-05-23 09:59 UTC, kirandash commented on code/040/module.js
Please rename the file to module.mjs since you are using ES6 `import` statement which is not available in .js files for node.js

Here's a link for you if you want to read more: 

https://stackoverflow.com/questions/45854169/how-can-i-use-an-es6-import-in-node-js

2023-05-23 09:59 UTC, kirandash commented on code/040/script.js
Please rename the file to script.mjs since you are using ES6 import statement which is not available in .js files for node.js

With .js files you have to use `require()`. If you want to use `import`, pls use .mjs extension

2023-05-23 09:59 UTC, kirandash commented on README.md
> +// module.js
Update readme file to match the changes I have requested under code folder

2023-05-25 17:49 UTC, Subham5401 commented
Thanks for your feedback! I'll do the necessary changes.

2023-05-28 11:57 UTC, kirandash approved these changes
LGTM

2023-05-28 11:58 UTC, merged