ISSUE 40
bgwebagency/who-wants-to-be-a-javascriptaire pull request #48
Opened 2023-05-28 18:11 UTC by naitikraj12935

MCQA 42 question

2023-05-28 18:21 UTC, naitikraj12935 commented
please merge the pull request

2023-05-29 03:50 UTC, kirandash requested changes

2023-05-29 03:50 UTC, kirandash commented on README.md
> +>>>>>>> main
seems like you forgot to remove `>>>>>>> main` after fixing merge conflict. Please remove this

2023-05-29 03:50 UTC, kirandash commented on README.md
> +=======
Remove =======

You can use a markdown preview in VSCode to see how your changes will look

Extension id:
shd101wyy.markdown-preview-enhanced

2023-05-29 03:50 UTC, kirandash commented on README.md
> +- D: import { default as myAlias } from 'module';
The question is good but I think we can improve the MCQ options to show both possible ways of adding alias with default imports:

```diff
- - A: import { myAlias as default } from 'module';
- - B: import default as myAlias from 'module';
- - C: import myAlias as default from 'module';
- - D: import { default as myAlias } from 'module';

+ - A: import default as myAlias from 'module';
+ - B: import myAlias from 'module';
+ - C: import { default as myAlias } from 'module';
+ - D: Both option B and C
```

2023-05-29 03:50 UTC, kirandash commented on README.md
> +The correct answer is D.
Update explanation to support the changes above to cover both ways of adding alias. Please also mention that option B is the recommended way of adding alias

Here is a SO post for you if you want to read more: https://stackoverflow.com/questions/39282253/how-can-i-alias-a-default-import-in-javascript

2023-06-02 13:09 UTC, kirandash commented
@naitikraj12935 any update on this? please let me know if you need any help. I can help you by making the changes if you are facing any issues

2023-06-03 06:50 UTC, closed without merging

2023-06-03 07:19 UTC, naitikraj12935 commented
I make a pull request again.so review it.

On Fri, 2 Jun 2023, 18:40 Kiran Dash, ***@***.***> wrote:

> @naitikraj12935 <https://github.com/naitikraj12935> any update on this?
> please let me know if you need any help. I can help you by making the
> changes if you are facing any issues
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bgwebagency/who-wants-to-be-a-javascriptaire/pull/48#issuecomment-1573710704>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3QBO7SWFGUPKF34LZWNTGDXJHQ2VANCNFSM6AAAAAAYR7UFTI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>